### PR TITLE
[Export] Refactor export class

### LINKED ISSUE #792: Search Results Hang
**Describe the bug**
Scraper results screen hangs and displays "Custom Movie Scraper" and no results

**To Reproduce**
1. Select Title (Movie)
2. Right Click, Select Load Information
3. No search results, just a Search Result screen with action spinner running

**Expected behavior**
Present a result set for found titles

**Screenshots**
image

**MediaElch Version:**
 - [ ] 2.6.3-dev (nightly)
 - [XX ] 2.6.2 stable

**Operating System:**
 - [XX ] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context**

### PR DESCRIPTION
**Pull request by bugwelle**
- separate UI from business logic
 - add more metadata tags

### Changes not related to export feature
 - [CustomMovieScraper] Fix hanging window if no valid scraper is found
   - fix #792
 - some debug output
 - docker fixes (permissions)
 - add CI document (docs/contrib)

### CODE REVIEW

File: src/globals/VersionInfo.cpp [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+    // minor version same
+    if (m_versionPatch > rhs.m_versionPatch) {
+        return true;
+    }
+    if (m_versionPatch < rhs.m_versionPatch) {
+        return false;
+    }
+
+    // should not be reached
+    Q_ASSERT(false);
```
Comment (founderio) [inline src/globals/VersionInfo.cpp]: @bugwelle What happens if you pass equal versions in here?

Comment (bugwelle) [reply src/globals/VersionInfo.cpp]: o.O

I totally missed that case. How the heck did I miss that case? I even have tests for this and I still missed this. Thank you @founderio . Will be fixed ASAP.

Comment (bugwelle) [reply src/globals/VersionInfo.cpp]: Now fixed.
