### PR TITLE
[IMDb] Prepare scraper for next IMDb do-over

### LINKED ISSUE #1088: IMDB - New Layout
**Scrapers that don't work:**

 - [x] IMDb
 - [ ] OFDb
 - [ ] TMDb
 - [ ] TMDbConcerts
 - [ ] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [ ] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
I found today in IMDB a yellow bar in the header, with the following text:  
> Get a sneak peek of the new version of this page  

It looks like the Layout is going to be modified.
And it will probably cause some change to the Scraper. Once again.
Sorry to be the bearer of this bad news.  **:-)**

### PR DESCRIPTION
**Pull request by bugwelle**
Fix #1088

- [x] Overview
- [x] Outline
- [x] Title
- [x] Released
- [x] Rating
- [x] VoteCount
- [x] Tagline
- [x] Runtime
- [x] director
- [x] writer
- [x] genres

### CODE REVIEW

File: src/scrapers/movie/imdb/ImdbMovieScraper.cpp [hunk 1]
```diff
@@ -6,14 +6,30 @@
 
 #include <QRegularExpression>
 
+
+static void addCookies(QNetworkRequest& req)
```
Comment (bugwelle) [inline src/scrapers/movie/imdb/ImdbMovieScraper.cpp:10]: This is just temporary and will be removed soon.

**Comment by euphoria360** [comment]
Any update on this. IMDB stopped working recently.

**Comment by bugwelle** [comment]
Movie scraping works again. I'm now looking at TV show scraping.
