### PR TITLE
[MovieFilter] Fix folder exclusion

### LINKED ISSUE #1111: Movie excluding filter on folders doesn't work for nested directories
**Describe the bug**
Folder excluding filter (ie. \<exclude\>\<pattern applyTo=\"folders\"\>...\</exclude\>) in advancedsettings.xml doen't work.

**To Reproduce**
1. Define a folder excluding pattern in advancedsettings.xml.
   - Eg. `<pattern applyTo="folders">test-movies</pattern> `
2. Start MediaElch.
3. Perform rescan.

**Expected behavior**
Excluded folders are not be shown in the movie list.

**MediaElch Version:**
 - 2.8.2 stable

**Operating System:**
 - Linux (distribution: Linux Mint 20)

**Additional context**
On the other hand, filename filter works.

### PR DESCRIPTION
**Pull request by bugwelle**
Fix #1111

### CODE REVIEW

File: src/movies/file_searcher/MovieFileSearcher.cpp [hunk 1]
```diff
@@ -291,7 +291,10 @@ int MovieFileSearcher::loadMoviesFromDirectory(const SettingsDir& movieDir,
         if (isFile && Settings::instance()->advanced()->isFileExcluded(fileName)) {
             continue;
         }
-        if (isDir && Settings::instance()->advanced()->isFolderExcluded(dirName)) {
+        // TODO: If there is a BluRay structure then the directory filter may not work
```
Comment (bugwelle) [inline src/movies/file_searcher/MovieFileSearcher.cpp:294]: TODO
